
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-keycloak
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-keycloak-network

  adminer:
    image: adminer
    container_name: adminer-keycloak
    ports:
      - "33011:8080"
    depends_on:
      - mysql
    networks:
      - mysql-keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_PORT: 3306
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_DATABASE: keycloak
    ports:
      - "8085:8080"  # correct internal port is 8080
    depends_on:
      - mysql
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import  # to import realm JSON
    networks:
      - mysql-keycloak-network


  servicereg:
    image: shaziya0108/servicereg
    container_name: servicereg
    ports:
      - "8761:8761"   # or whatever port your service exposes
    networks:
      - mysql-keycloak-network
    depends_on:
      - mysql   # if it depends on mysql or others


networks:
  mysql-keycloak-network:

volumes:
  mysql_data:
